# Generated by Django 4.1.3 on 2022-11-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deathcnt', models.IntegerField(blank=True, db_column='deathCnt', null=True)),
                ('defcnt', models.IntegerField(blank=True, db_column='defCnt', null=True)),
                ('gubun', models.TextField(blank=True, null=True)),
                ('gubuncn', models.TextField(blank=True, db_column='gubunCn', null=True)),
                ('gubunen', models.TextField(blank=True, db_column='gubunEn', null=True)),
                ('incdec', models.IntegerField(blank=True, db_column='incDec', null=True)),
                ('isolclearcnt', models.IntegerField(blank=True, db_column='isolClearCnt', null=True)),
                ('isolingcnt', models.IntegerField(blank=True, db_column='isolIngCnt', null=True)),
                ('localocccnt', models.IntegerField(blank=True, db_column='localOccCnt', null=True)),
                ('overflowcnt', models.IntegerField(blank=True, db_column='overFlowCnt', null=True)),
                ('qurrate', models.TextField(blank=True, db_column='qurRate', null=True)),
                ('stdday', models.TextField(blank=True, db_column='stdDay', null=True)),
            ],
            options={
                'db_table': 'test1',
                'managed': False,
            },
        ),
    ]
