# Generated by Django 4.1.3 on 2022-11-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test1',
            options={},
        ),
    ]
